### ISSUE TITLE
error: no function clause matching in Dogma.Rule.FunctionParentheses

### ISSUE THREAD

**Issue by CharlesIrvineKC** [aaronjensen/flycheck-dogma#1]
For this code:

```
defmodule KV.BucketTest do
  use ExUnit.Case, async: true

  test "foo"
```

as soon as I type a space after "foo", I get:

```
14:08:54.367 [error] Task #PID<0.86.0> started from #PID<0.70.0> terminating
** (FunctionClauseError) no function clause matching in Dogma.Rule.FunctionParentheses.check_function_parens/2
    lib/dogma/rule/function_parentheses.ex:37: Dogma.Rule.FunctionParentheses.check_function_parens(nil, [])
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/dogma/script.ex:105: Dogma.Script.run_tests/2
    lib/dogma/rules.ex:22: Dogma.Rules.test_script/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<1.35272571/0 in Dogma.Rules.test/3>
    Args: []
```

**Comment by aaronjensen** [comment]
Hi @ChuckIrvine, that sounds like it may be a bug in dogma. Could you report it there please? Thanks!
